---
- name: Install Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
     - git
     - curl

- name: Clone Dehydrated
  git:
    repo: https://github.com/lukas2511/dehydrated
    dest: /opt/dehydrated

- name: Create Dehydrated Config File
  copy:
    src: dehydrated.conf
    dest: /opt/dehydrated/config

- name: Create DuckDns Hook
  copy:
    src: duckdns-hook.sh
    dest: /opt/dehydrated/duckdns-hook.sh
    mode: 755 

- name: Create DuckDns Refresh Job
  copy:
    src: duckdns-refresh.sh
    dest: /opt/dehydrated/duckdns-refresh.sh
    mode: 755 

- name: Copy Dehydrated domains file
  copy:
    src: domains.txt
    dest: /opt/dehydrated/domains.txt

- name: Copy DuckDNS token file
  copy:
    src: duckdns-token.txt
    dest: /opt/dehydrated/duckdns-token.txt

- name: Try to find existing LetsEncrypt accounts
  find: 
    paths: /opt/dehydrated/accounts
    file_type: directory 
  register: existing_accounts

- name: Register and Accept LetsEncrypt terms
  shell: /opt/dehydrated/dehydrated --register --accept-terms
  when: existing_accounts.matched|int == 0

- name: Initial certificate generation
  shell: /opt/dehydrated/dehydrated -c

- name: Create Cron for renewals
  cron:
    name: LetsEncrypt renewal
    day: 1
    hour: 0
    minute: 0
    job: "/opt/dehydrated/dehydrated -c"
    state: present

- name: Create Cron for DuckDns refresh
  cron:
    name: DuckDNS refresh
    minute: "*/10"
    job: /bin/bash -c "/opt/dehydrated/duckdns-refresh.sh"
    state: present
